package telegram

import (
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"os"
)

// SendVoice streams an OGG audio directly to Telegram without saving to disk
// using io.Pipe to pass the multipart body to the HTTP request.
func SendVoice(chatID int64, audioReader io.Reader) error {
	// 1: Create a pipe to stream the multipart form construction
	// directly into the HTTP request body.
	pr, pw := io.Pipe()

	// 2: Create a multipart writer that writes to the pipe writer
	writer := multipart.NewWriter(pw)

	// We MUST close the pipe writer *after* the multipart writer is closed,
	// so the HTTP client knows the body is complete and stops reading.
	// We run this in a goroutine because pr is being consumed synchronously below.
	go func() {
		defer pw.Close()
		defer writer.Close()

		// Write chat_id
		err := writer.WriteField("chat_id", fmt.Sprintf("%d", chatID))
		if err != nil {
			pw.CloseWithError(fmt.Errorf("failed to write chat_id field: %w", err))
			return
		}

		// Create form file field for "voice"
		part, err := writer.CreateFormFile("voice", "audio.ogg")
		if err != nil {
			pw.CloseWithError(fmt.Errorf("failed to create form file: %w", err))
			return
		}

		// Stream from the audioReader (e.g. Gemini response body) -> multipart file part
		_, err = io.Copy(part, audioReader)
		if err != nil {
			pw.CloseWithError(fmt.Errorf("failed to copy audio stream to part: %w", err))
			return
		}
	}()

	// 3: Create the HTTP POST request.
	// We pass the pipe reader (pr) directly to the request body.
	// NewRequestWithContext is preferred to handle timeout/cancellation gracefully later if needed.
	url := fmt.Sprintf("https://api.telegram.org/bot%s/sendVoice", getBotToken())
	req, err := http.NewRequest(http.MethodPost, url, pr)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set the correct Content-Type including the boundary generated by multipart.Writer
	req.Header.Set("Content-Type", writer.FormDataContentType())

	// 4: Send the HTTP request
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send voice to telegram: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		// Just for logging if it fails; otherwise we ignore body
		bodyBytes, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("telegram returned status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	return nil
}
